sudo: false

language: php

php:
  - 7
  - 7.1
  - nightly

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  allow_failures:
    - php: nightly

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
  matrix:
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - DEPENDENCIES=""

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8d73a1cafd9bff5c96ee
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update -o --prefer-source $COMPOSER_ARGS $DEPENDENCIES
  - composer show

script:
  - mkdir -p build/logs
  # Run tests
  - php ./vendor/bin/phpunit --configuration tests/phpunit.xml

after_script:
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then php vendor/bin/coveralls -v; fi
