<?php
/* @var $container Zend\Navigation\Navigation */
$container = $this->container;
?>
<?php foreach ($container as $page): ?>
    <?php if (!$this->navigation()->accept($page)) {
        continue;
    }
    ?>
    <div class="col-sm-3">
        <h3 class="footerheadlines <?= $page->getClass() ?>">
        <?= $this->escapeHtml(
                $this->translate(
                    $page->getLabel(),
                    $this->navigation($container)->getTranslatorTextDomain()
                )
            );
        ?>
        </h3>
        <ul class="list-unstyled">
            <?php /** @var Zend\Navigation\Page\AbstractPage $child */ ?>
            <?php foreach ($page->getPages() as $child): ?>
                <?php if (!$this->navigation()->accept($child)) {
                    continue;
                } ?>
                <li class="footertext<?php if ($child->isActive(true)) echo ' active'; ?>">
                    <a href="<?= $child->getHref() ?>"
                        <?php if (null !== $child->getTarget()): ?>
                            target="<?= $child->getTarget(); ?>"
                        <?php endif; ?> >
                        <?= $this->escapeHtml(
                            $this->translate(
                                $child->getLabel(),
                                $this->navigation($container)->getTranslatorTextDomain()
                            )
                        );
                        ?>
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
<?php endforeach ?>