<?php
/** @var \Zend\Form\Form $form */
$form = $this->formWidget;
$form->prepare();
$form->setAttribute('method', 'post');
?>

<?= $this->form()->openTag($form) ?>
<?php foreach ($form as $element): ?>
    <?php
    /** @var \Zend\Form\Element $element */
    if($element->getAttribute('type') == 'hidden'): ?>
        <?= $this->formInput($element) . $this->pserverformerrors($element) ?>
        <?php
        continue;
    endif;
    ?>
    <div class="form-group">
        <?php if (!$element instanceof Zend\Form\Element\Button && !$element instanceof Zend\Form\Element\Checkbox): ?>
            <label><?= $this->formLabel($element) ?></label>
        <?php endif ?>

        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            <?= $this->formButton($element) ?>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <div>
                <?= $this->formCaptcha($element) . $this->pserverformerrors($element) ?>
            </div>
        <?php elseif ($element instanceof PServerCore\Form\Element\DateTimeJQuery): ?>
            <?= $this->formInput($element) . $this->pserverformerrors($element) ?>
        <?php elseif ($element instanceof Zend\Form\Element\DateTimeLocal): ?>
            <?= $this->formDateTimeLocal($element) . $this->pserverformerrors($element) ?>
        <?php elseif ($element instanceof Zend\Form\Element\DateTime): ?>
            <?= $this->formDateTime($element) . $this->pserverformerrors($element) ?>
        <?php elseif ($element instanceof DoctrineModule\Form\Element\ObjectSelect || $element instanceof Zend\Form\Element\Select): ?>
            <?= $this->formSelect($element) . $this->pserverformerrors($element) ?>
        <?php elseif ($element instanceof Zend\Form\Element\Textarea): ?>
            <?= $this->formTextarea($element) . $this->pserverformerrors($element) ?>
        <?php elseif ($element instanceof Zend\Form\Element\Checkbox): ?>
            <div class="form-check">
                <label>
                    <?= $this->formCheckbox($element) . $this->formLabel($element) . $this->pserverformerrors($element) ?>
                </label>
            </div>
        <?php else: ?>
            <?= $this->formInput($element) . $this->pserverformerrors($element) ?>
        <?php endif ?>
    </div>
<?php endforeach ?>
<?= $this->form()->closeTag() ?>