<div class="margin-bottom-15">
    <h3><?= $this->escapeHtml($this->user->getUsername()) ?></h3>
    <hr/>
    <ul id="coinsWidgetSidebar" class="list-unstyled">
        <?= $this->coinsInfoWidgetPServerCore() ?>
    </ul>
    <?php if ($this->isAllowed('PServerCore/coins')) : ?>
        <i class="fa-refresh fa coins-widget-reload" data-url="<?= $this->url('PServerCore/coins', ['action' => 'reload-widget']); ?>"></i>
    <?php endif; ?>
    <hr/>
    <div class="sidebar-nav">
        <div class="navbar navbar-default" role="navigation">
            <div class="navbar-collapse collapse sidebar-navbar-collapse">
                <?= $this->navigationWidgetPServerCore()->menu()->setPartial('p-server-core/account-navigation') ?>
            </div>
        </div>
    </div>
</div>