<div class="margin-top-30">
    <h3><?= $this->translate('Servertime') ?></h3>
    <hr/>
    <ul class="list-unstyled">
        <li><i class="fa fa-clock-o"></i> <?= $this->translate('Servertime') ?>: <span id="idTimerClock"><?= date('H:i:s') ?></span></li>
        <?php $i = 0; ?>
        <?php if ((bool)$this->timer): ?>
            <?php foreach ($this->timer as $curTimer) : ?>
                <li><i class="<?= $this->escapeHtml($curTimer['icon']) ?>"></i>
                    <?= $curTimer['name'] ?>:
                    <?php if ($curTimer['time'] > 0): ?>
                        <span class="timerCountdown" id="<?= 'idTimeCountdown_' . $i++; ?>" data-time="<?= $curTimer['time'] ?>"></span>
                    <?php else: ?>
                        <?= $this->escapeHtml($curTimer['text']) ?>
                    <?php endif; ?>
                    <?php if (isset($curTimer['timers'])) : ?>
                        <ul>
                            <?php foreach ($curTimer['timers'] as $subTimer) : ?>
                                <li><i class="<?= $this->escapeHtml($subTimer['icon']) ?>"></i>
                                    <?= $subTimer['name'] ?>:
                                    <?php if ($subTimer['time'] > 0): ?>
                                        <span class="timerCountdown" id="<?= 'idTimeCountdown_' . $i++; ?>" data-time="<?= $subTimer['time'] ?>"></span>
                                    <?php else: ?>
                                        <?= $this->escapeHtml($subTimer['text']) ?>
                                    <?php endif; ?>
                                </li>
                            <?php endforeach ?>
                        </ul>
                    <?php endif ?>
                </li>
            <?php endforeach ?>
        <?php endif ?>
    </ul>
</div>